import { Request, Response } from 'express';
import authServerUtil from '@server/lib/auth/authServerUtil.js';
import { Session, UserTheme } from '@server/database/schemas/index.js';
import { awsHelper, imageHelper, userHelper } from '../helpers/index.js';
import type { AccessTokenType } from '@shared/types/server/auth/AccessTokenType.js';
import { db } from '@server/database/db.js';
import { eq } from 'drizzle-orm';
import { loggerFactory } from '@server/lib/logger/index.js';

export const createAuthService = (req?: Request, res?: Response) => {
	/**
	 * Type guard for JWT payloads generated by this service.
	 */
	const isAccessTokenPayload = (
		payload: unknown,
	): payload is AccessTokenType => {
		if (!payload || typeof payload !== 'object') return false;
		const candidate = payload as Record<string, unknown>;
		return (
			typeof candidate.sessionId === 'string' &&
			typeof candidate.sessionType === 'string' &&
			typeof candidate.exp === 'number'
		);
	};
	type AuthContext = {
		sessionId: string;
		userId?: string;
		storageId?: string;
	};
	const authService = {
		// Per-request context for downstream auth helpers
		req,
		res,
		util: authServerUtil,
		aws: awsHelper,
		image: imageHelper,
		user: userHelper,

		/**
		 * Validate token, hydrate request with session info, or create a new session.
		 */
		async authCheck(accessToken: string) {
			// Validate token, hydrate request with session info, or create a new session

			try {
				const decodedToken = await this.util.verifyToken(accessToken);
				if (!decodedToken) {
					await this.createUserSession();
					return;
				}
				if (isAccessTokenPayload(decodedToken)) {
					const sessionId = decodedToken.sessionId;

					const [sessionData] =
						await this.getUserSessionData(sessionId);

					// Get storageId
					let storageId: string | undefined;

					if (sessionData.userId) {
						const foundUser = await this.user.getUserData({
							userId: sessionData.userId,
						});

						storageId = foundUser?.storageId ?? undefined;
					}

					if (this.req && sessionData) {
						this.req.body ??= {};

						this.req.body.userId = sessionData.userId ?? undefined;
						this.req.body.sessionId = sessionId;

						//Used with controllers that make calls to AWS
						const authContext: AuthContext = {
							userId: sessionData.userId ?? undefined,
							sessionId,
							storageId,
						};

						(this.req as any).authContext = authContext;

						loggerFactory.authService.info(
							`[Auth Check] - sessionType: ${
								sessionData.userId ? 'Authenticated' : 'Guest'
							} - sessionId: ${sessionId}`,
						);

						return;
					}

					await this.createUserSession();
					return;
				} else {
					await this.createUserSession();
				}
			} catch {}
		},
		/**
		 * Create a user or guest session and set the session cookie.
		 */
		async createUserSession(userId?: string) {
			// Replace any existing session cookie before issuing a new one
			this.removeSessionCookie();
			const expirationMs = this.util.getSessionExpirationMs();
			const tokenTtlMs = Math.max(0, expirationMs - Date.now());

			const ipAddress =
				this.req?.headers['x-forwarded-for']
					?.toString()
					.split(',')[0]
					?.trim() ||
				this.req?.socket.remoteAddress ||
				null;

			const userAgent = this.req?.headers['user-agent'] ?? null;

			if (userId) {
				const [session] = await db
					.insert(Session)
					.values({
						userId,
						expirationTime: new Date(expirationMs),
						ipAddress,
						userAgent,
					})
					.returning();

				if (!session) return;
				// Use absolute expiration time for JWT and TTL for cookie
				const tokenExpirationSeconds = Math.floor(expirationMs / 1000);

				const payload = {
					sessionType: 'Authenticated',
					sessionId: session.sessionId,
					exp: tokenExpirationSeconds,
				};

				console.log(payload);
				// Sign access token and set cookie
				const accessToken = await this.util.generateToken(payload);

				this.setSessionCookie(accessToken, tokenTtlMs);

				loggerFactory.authService.info(
					`[New Session] - sessionType: Authenticated - userId: ${userId}`,
				);
			} else {
				// Create guest session
				const [session] = await db
					.insert(Session)
					.values({
						expirationTime: new Date(expirationMs),
						ipAddress,
						userAgent,
					})
					.returning();

				if (!session) return;
				// Use absolute expiration time for JWT and TTL for cookie

				// Create user theme for guest session
				await db.insert(UserTheme).values({
					sessionId: session.sessionId,
				});

				const tokenExpirationSeconds = Math.floor(expirationMs / 1000);

				const payload = {
					sessionType: 'Guest',
					sessionId: session.sessionId,
					exp: tokenExpirationSeconds,
				};

				console.log(payload);
				// Sign access token and set cookie
				const accessToken = await this.util.generateToken(payload);

				this.setSessionCookie(accessToken, tokenTtlMs);
				loggerFactory.authService.info(
					`[New Session] - sessionType: Guest - sessionId: ${payload.sessionId}`,
				);
			}
		},
		/**
		 * Fetch session data for a given session ID.
		 */
		async getUserSessionData(sessionId: string) {
			// TODO: check if session expired and handle accordingly
			return await db
				.select()
				.from(Session)
				.where(eq(Session.sessionId, sessionId));
		},
		/**
		 * Delete a session by ID and return the deleted record.
		 */
		async deleteUserSession(sessionId: string) {
			// Implementation for deleting a user session
			return await db
				.delete(Session)
				.where(eq(Session.sessionId, sessionId))
				.returning();
		},
		/**
		 * Persist the access token on the client as an HTTP-only cookie.
		 */
		setSessionCookie(accessToken: string, tokenExpiration: number) {
			// Persist access token on the client
			this.res?.cookie('sessionCookie', accessToken, {
				httpOnly: true,
				secure: process.env.NODE_ENV === 'production',
				sameSite: 'lax',
				maxAge: tokenExpiration,
			});
		},
		/**
		 * Remove the access token cookie from the client.
		 */
		removeSessionCookie() {
			// Remove access token cookie
			this.res?.clearCookie('sessionCookie', {
				httpOnly: true,
				secure: process.env.NODE_ENV === 'production',
				sameSite: 'lax',
				path: '/', // 👈 important
			});
		},
		clearReqBody() {
			if (this.req) {
				this.req.body = undefined;
			}
		},
	};

	return authService;
};
